version: '3'

services:
    web:
        depends_on: 
            - db
        build:
            context: ./web
            dockerfile: DockerFile
        container_name: 'web'
        volumes:
            - ./web:/code
        environment:
            FLASK_ENV: development
        ports: 
            - 5000:5000
        restart: always
        networks:
            - app-network

    db:
        image : mysql
        volumes: 
            - ./database:/var/lib/mysql
        environment: 
            MYSQL_USER: 'manpro'
            MYSQL_PASSWORD: 'manpro'
            MYSQL_ROOT_PASSWORD: 'manpro'
            MYSQL_DATABASE: 'ecommerance'
        expose:
            - 3306
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        networks:
            - app-network

    adminer:
        image: adminer
        restart: always
        ports: 
            - 8080:8080
        networks:
            - app-network

    redis:
        image: "redis:alpine"
        restart: always
        networks: 
            - app-network

networks:
    app-network:
        driver: bridge