FROM python:3.7

WORKDIR /code

ENV FLASK_APP=main.py
ENV FLASK_RUN_HOST=0.0.0.0
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
EXPOSE 5000

COPY . .

CMD ["pip", "freeze", ">", "re.txt"]
CMD [ "python3", "-m" , "flask", "run"]
